### PR TITLE
Respect default values provided to get() methods

### PR DESCRIPTION
**Pull request by jcwilson**
The implementations of get() on Namespace and Experiment take a
defaultValue parameter which eventually filters down and is passed to an
Assignment.get() call. However, Assignment.get() does not take a second
argument and the defaultValue is summarily ignored.

These changes update Assignment.get() to take a second argument for
defaultValue and it maintains the same semantics as Interpreter.get():
if the named param is not found or is found but it is null or undefined,
get() will return defaultValue.

### CODE REVIEW

**Comment by rawls238** [comment]
nice change. Thanks for the contribution!

**Comment by jcwilson** [comment]
Awesome! Thanks for accepting it :)

Do I need to do anything else to help get a new version up to npmjs.com?

**Comment by rawls238** [comment]
@jcwilson I'll update the version this afternoon

**Comment by rawls238** [comment]
@jcwilson new version is now on npm!

**Pull request merged**
