### PR TITLE
Namespace perf improvements

### PR DESCRIPTION
**Pull request by rawls238**
@TimBeyer @eytan 

Spent a lot of time today trying to get this to be fast AND compatible with other implementations of PlanOut. After a lot of hackery, I still was not able to get it to work unfortunately - I'm gonna hopefully try again soon to do this. 

However, if we make compatibility an optional value then we can speed things up dramatically since the primary lag was from BigNumber. Consumers can enable this by doing 

```
ExperimentSetup.toggleCompatibleHash(false);
```

This is the result I got with compatibility turned off: 19.26401599845849 ms over 500 runs
This is the result I got with compatibility turned on: 146.8896060003899 ms over 500 runs

Ideally we can extend this even further to allow for user-supplied hash functions but this is a good step forward. There are some other things to increase perf but they'll mainly be micro-opts compared to this change.

### CODE REVIEW

**Comment by eytan** [comment]
This seems like a reasonable solution... Just out of curiosity, how does
the performance compare if you completely took out the compatibility mode?
I wonder whether you should just have separate classes / implementations.

**Comment by rawls238** [comment]
@eytan I was originally thinking the same thing...but there's almost no perf overhead to having both. The only overhead is in terms of how many bytes we would have to carry over the wire having to carry around BigNumber, but BigNumber is a fairly small package so removing it wouldn't affect overall package size too much.

**Comment by rawls238** [comment]
There are a fewer other optimizations I want to get to before releasing this as a new version @TimBeyer but they should hopefully be done by Monday...

**Comment by rawls238** [comment]
Also I'll add details around the compatibility stuff to the README, but I want to revisit this at some point to see if I can actually come up with a non-hacky yet performant solution to maintaining compatibility

**Comment by eytan** [comment]
Ok then! Yeah, my thought was to separate and create two bundles, which
could improve size and performance. But this works! I really appreciate the
extra time you spent making it so that PlanOut.js could still be compatible
with other implementations of PlanOut.

**Comment by TimBeyer** [comment]
@rawls238 has this been working correctly for you? I just wanted to migrate to using `toggleCompatibleHash(false)` and suddenly all assignments seemed to fail for us. When I don't switch it everything works fine. Will investigate a bit further and see where the problem is.

**Comment by rawls238** [comment]
@TimBeyer it has been working for us - are you on 3.0.1? The default behavior is for the compatiblehash to be false so it doesn't make much sense that ```toggleCompatibleHash(false)``` would break anything. Let me know what you find

**Comment by TimBeyer** [comment]
@rawls238 I'm on current master. In the end, I did a fresh build and things started working again. I guess the current build is broken and the fix happened after https://github.com/HubSpot/PlanOut.js/pull/22 which was the last time the build was created.

**Comment by TimBeyer** [comment]
Taking a quick look I assume it must have been https://github.com/HubSpot/PlanOut.js/commit/6648fdaa2e113d788c40fdce17d1a27a89667d49#diff-ede1f2c67e8fc69fcf959df467e94f5aR77

**Comment by rawls238** [comment]
@TimBeyer yup, must have not built before releasing. New release will be up soon, sorry about that

**Comment by rawls238** [comment]
@TimBeyer correct transpiled version should be published via npm now. Good argument for having the tests point to the latest transpiled version instead of directly at the source perhaps..

**Comment by TimBeyer** [comment]
@rawls238 awesome, thanks. Yeah, was thinking the same about the tests. Was very confused when the tests actually passed and I needed to write a new test pointing to the build to actually reproduce this.

**Pull request merged**
