### PR TITLE
Only key into value to read salt if value exists

### PR DESCRIPTION
**Pull request by mattrheault**
It seems that ie10 will try to read ```salt``` from ```value``` when ```value``` is null in ie10.

---
@rawls238 @geoffdaigle @marcneuwirth

### CODE REVIEW

**Comment by geoffdaigle** [comment]
👍  But not sure whats up with Travis being sad

**Comment by rawls238** [comment]
welp

**Comment by mattrheault** [comment]
Ahhhh... well I also forgot to build the project before pushing.

@rawls238 would you mind pulling this down, building, & pushing? The machine I'm on is on the earlier version of node which our build stack doesn't support.

**Comment by rawls238** [comment]
kicked off another build. Assuming you guys want this change in ASAP? Bump the version to 3.0.1 and we'll publish it.

**Comment by rawls238** [comment]
Not sure what the intermittent node v4 error is but I don't think it has anything to do with this PR and I don't have any time right now to look into it, so going to open an issue and push this through so that you guys can have this fix.

**Comment by mattrheault** [comment]
Thanks for the help Guy!

**Comment by rawls238** [comment]
@mattrheault published

**Pull request merged**
